name: main-workflow

on:
  workflow_dispatch:
    inputs:
      skip-second-job:
        description: Skip the second job
        required: true
        default: true
        type: boolean

jobs:
  first-job:
    name: first-job
    runs-on: ubuntu-latest
    steps: 
      - run: echo "I'm the first job that runs every time!"
  second-job:
    name: second-job
    runs-on: ubuntu-latest
    needs:
      - first-job
    if: github.event.inputs.skip-second-job == 'false' 
    steps:
      - run: echo "I am the second job and I run only sometimes!
  third-job:
    name: third-job
    runs-on: ubuntu-latest
    needs:
      - first-job
      - second-job
    if: always() && (needs.second-job.result == 'success' || needs.second-job.result == 'skipped')
    steps:
      - run: echo "I'm the third job!"